development: &dev
  secret_key_base: fd0f51a314e0852b595185f2c415ef035527c3e21b6fb7a7b15c1a1833d5a649081e0abb6437750c8a24dc6ec0c3e93edee9f5e3255a9d604e1f6df0050991bf

test:
  secret_key_base: 4effd2e038d34d8a5765249d69f7a187934657e9d75e50ac944b7db0d37812f5a380e1b42413e2655b4261accbd69c42b9a3bc3da89b4aa2f73ba6f64a26cece

staging:
  <<: *dev

production:
  <<: *dev
